myaccount/urls.py
from django.urls import re_path
from . import views

app_name = "myaccount"
urlpatterns = [
    re_path(r'^profile/$', views.profile, name='profile'),
    re_path(r'^profile/update/$', views.profile_update, name='profile_update'),

]

restaurants/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),
    url('accounts/', include('allauth.urls')),
    url('accounts/', include('myaccount.urls')),
    url('restaurantsReviews/', include('restaurantsReviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurantsReviews/urls.py
from django.urls import path, re_path
from . import views

app_name = 'restaurantsReviews'

urlpatterns = [
    # Check all restaurants
    path('', views.RestaurantList.as_view(), name='restaurant_list'),
    # Check the detail of selected restaurant
    re_path(r'^restaurant/(?P<pk>\d+)/$', views.RestaurantDetail.as_view(), name='restaurant_detail'),
    # Create restaurant
    re_path(r'^restaurant/create/$', views.RestaurantCreate.as_view(), name='restaurant_create'),
    # Edit restaurant
    re_path(r'^restaurant/(?P<pk>\d+)/edit/$', views.RestaurantEdit.as_view(), name='restaurant_edit'),
    # Create dish
    re_path(r'^restaurant/(?P<pk>\d+)/dishes/create/$', views.DishCreate.as_view(), name='dish_create'),
    # Edit dish
    re_path(r'^restaurant/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/edit/$', views.DishEdit.as_view(), name='dish_edit'),
    # Details of dish
    re_path(r'^restaurant/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/$', views.DishDetail.as_view(), name='dish_detail'),
    # Create reviews
    re_path(r'^restaurant/(?P<pk>\d+)/reviews/create/$', views.review_create, name='review_create'),
    # Search restaurant
    path('search', views.restaurant_search, name='restaurant_search'),
    # Ajax return result
    path('ajax/search', views.restaurant_ajax_research, name='restaurant_ajax_search')
]

restaurantsReviews/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.urls import reverse


class Restaurant(models.Model):
    name = models.TextField()
    address = models.TextField(blank=True, default='')
    phone = models.TextField(blank=True, default='')
    url = models.URLField(blank=True, null=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('restaurantsReviews:restaurant_detail', args=[str(self.id)])


class Dish(models.Model):
    name = models.TextField()
    description = models.TextField(blank=True, default='')
    price = models.DecimalField('USD amount', max_digits=8, decimal_places=2, blank=True, null=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="restaurantsReviews", blank=True, null=True)
    restaurant = models.ForeignKey(Restaurant, null=True, related_name='dishes', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("restaurantsReviews:dish_detail", args=[str(self.restaurant.id), str(self.id)])


class Review(models.Model):
    RATING_CHOICE = ((1, 'one'), (2, 'two'), (3, 'Three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=True, default=5, choices=RATING_CHOICE)
    DEFAULT_COMMENT = "The user doesn't leave any comment"
    comment = models.TextField(blank=True, null=True, default=DEFAULT_COMMENT)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)

    class Meta:
        abstract = True


class RestaurantReview(Review):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name="review")

    def __str__(self):
        return "{} review".format(self.restaurant.name)

restaurantsReviews/forms.py
from django.forms import ModelForm, TextInput, URLInput, ClearableFileInput, NumberInput
from .models import Restaurant, Dish


class RestaurantForm(ModelForm):
    class Meta:
        model = Restaurant
        exclude = ('user', 'date',)

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'address': TextInput(attrs={'class': 'form_control'}),
            'phone': TextInput(attrs={'class': 'form_control'}),
            'url': URLInput(attrs={'class': 'form_control'}),
        }

        labels = {
            'name': 'Name',
            'address': 'Address',
            'phone': 'Phone',
            'url': 'Website'
        }


class DishForm(ModelForm):
    class Meta:
        model = Dish
        exclude = ('user', 'date', 'restaurant',)

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'description': TextInput(attrs={'class': 'form-control'}),
            'price': NumberInput(attrs={'class': 'form-control'}),
            'image': ClearableFileInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'name': 'Dishes',
            'description': 'Description',
            'price': 'Price',
            'image': 'Image',
        }

restaurantsReviews/views.py
import json
from django.db.models import Q
from django.views.generic import DetailView, ListView, UpdateView
from django.views.generic.edit import CreateView
from .forms import RestaurantForm, DishForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Restaurant, RestaurantReview, Dish


class RestaurantList(ListView):
    queryset = Restaurant.objects.all().order_by('-date')
    context_object_name = 'latest_restaurant_list'
    template_name = 'restaurantsReviews/restaurant_list.html'


class RestaurantDetail(DetailView):
    model = Restaurant
    template_name = 'restaurantsReviews/restaurant_detail.html'

    def get_context_data(self, **kwargs):
        context = super(RestaurantDetail, self).get_context_data(**kwargs)
        context['RATING_CHOICE'] = RestaurantReview.RATING_CHOICE
        return context


class RestaurantCreate(CreateView):
    model = Restaurant
    template_name = 'restaurantsReviews/form.html'
    form_class = RestaurantForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(RestaurantCreate, self).form_valid(form)


class RestaurantEdit(UpdateView):
    model = Restaurant
    template_name = 'restaurantsReviews/form.html'
    form_class = RestaurantForm


class DishDetail(DetailView):
    model = Dish
    template_name = 'restaurantsReviews/dish_detail.html'


class DishCreate(CreateView):
    model = Dish
    template_name = 'restaurantsReviews/form.html'
    form_class = DishForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.restaurant = Restaurant.objects.get(id=self.kwargs['pk'])
        return super(DishCreate, self).form_valid(form)


class DishEdit(UpdateView):
    model = Dish
    template_name = 'restaurantsReviews/form.html'
    form_class = DishForm


def review_create(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    review = RestaurantReview(
        rating=request.POST['rating'],
        comment=request.POST['review'],
        user=request.user,
        restaurant=restaurant
    )

    review.save()
    return HttpResponseRedirect(reverse('restaurantsReviews:restaurant_detail', args=[pk]))


def restaurant_search(request):
    q = request.GET.get('q', None)
    if q:
        queryset = Restaurant.objects.filter(Q(name__contains=q))
        context = {'latest_restaurant_list': queryset}
        return render(request, 'restaurantsReviews/restaurant_search.html', context=context)
    return render(request, 'restaurantsReviews/restaurant_search.html')


def restaurant_ajax_research(request):
    q = request.GET.get('q', None)
    if q:
        restaurant_list = Restaurant.objects.filter(Q(name__contains=q))
        data = []
        for restaurant in restaurant_list:
            data.append({"name": restaurant.name})
        json_data = json.dumps(data)
        return HttpResponse(json_data)

restaurantsReviews/templates/restaurantsReviews/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Restaurants Reviews {% endblock %}</title>
    <meta name="keywords" content="{% block keywords %} some keywords{% endblock %} ">
    <meta name="description" content="{% block description %} Django web application example.{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=2">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body class="bs-docs-home">
<nav class="navbar navbar-inverse navbar-static-top bs-docs-nav">
 <div class="container">
     <div class="navbar-header">
         <!--
         <button type="button" clas="navbar-toggle" data-toggle="collagpse" data-target="#myNavbar">
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
         </button>
         -->
         <a class="navbar-brand" href="{% url 'restaurantsReviews:restaurant_list' %}"><strong>Restaurant Reviews</strong></a>
     </div>
 </div>

 <div class="collapse navbar-collapse ex1" id="myNavbar">
    <ul class="nav navbar-nav navbar-light">
        <a href="{% url 'restaurantsReviews:restaurant_search' %}">
            <span class="glyphicon glyphicon-search"></span>
            Search Restaurants
        </a>
    </ul>
     <ul class="nav navbar-nav navbar-right">
         {% if request.user.is_authenticated %}
             <li class="dropdown">
                 <a class="dropdown-toggle btn-green" data-toggle="dropdown" href="#">
                     <span class="glyphicon glyphicon-user"></span>
                     {{ request.user.username }} <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'myaccount:profile' %}">My Profile</a></li>
                    <li><a href="'{% url 'account_logout' %}">Log out</a></li>
                </ul>
             </li>
         {% else %}
             <li clas="dropdown">
                <a class="dropdown-toggle btn-green" href="'{% url 'account_signup' %}">
                    <span class="glyphicon glyphicon-user"></span> Register
                </a>
             </li>
             <li clas="dropdown">
                <a class="dropdown-toggle btn-green" href="'{% url 'account_login' %}">
                    <span class="glyphicon glyphicon-user"></span> Log in
                </a>
             </li>
         {% endif %}
     </ul>

 </div>
</nav>

<main id="section1" class="contianer_fluid">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="newsbox">
                    <div class="container1">
                        {% block content %}
                            {% if error_message %}
                                <p><strong>{{ error_message }}</strong></p>
                            {% endif %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<footer class="footer">
  {% block footer %}

  {% endblock %}
</footer>

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

restaurantsReviews/templates/restaurantsReviews/dish_detail.html
{% extends 'restaurantsReviews/base.html' %}

{% block content %}
    <h3>
        {{ dish.name }}
        {% if request.user == dish.user %}
            (<a href="{% url 'restaurantsReviews:dish_edit' dish.restaurant.id dish.id%}">Edit Dish</a>)
        {% endif %}
    </h3>

    <p>
        Restaurant:
        <a href="{% url 'restaurantsReviews:restaurant_detail' dish.restaurant.id %}">
            {{ dish.restaurant.name }}
        </a>
    </p>

    {% if dish.image %}
        <p>
            <img src="{{ dish.image.url }}"/>
        </p>
    {% endif %}

    <p>Price: ${{ dish.price }}</p>
{% endblock %}

restaurantsReviews/templates/restaurantsReviews/form.html
{% extends 'restaurantsReviews/base.html' %}

{% block content %}

<form action="" method='POST' enctype="multipart/form-data" >
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

restaurantsReviews/templates/restaurantsReviews/restaurant_detail.html
{% extends "restaurantsReviews/base.html" %}

{% block content %}
    <h3>
        {{ restaurant.name }}
        {% if request.user == restaurant.user %}
            (<a href="{% url 'restaurantsReviews:restaurant_edit' restaurant.id %}">Edit Restaurant</a>)
        {% endif %}
    </h3>

    <h5 style="margin-left: 40px">Address</h5>
    <p style="margin-left: 60px">{{ restaurant.address }}</p>
    <h5 style="margin-left: 40px">Phone</h5>
    <p style="margin-left: 60px">{{ restaurant.phone }}</p>
    <h5 style="margin-left: 40px">Website</h5>
    {% if restaurant.url %}
        <a style="margin-left: 60px" href = {{ restaurant.url }}>{{ restaurant.url }}</a>
    {% else %}
        <p style="margin-left: 60px">This restaurant hasn't add website</p>
    {% endif %}

    <br>

    <h4>Menu
        {% if request.user.is_authenticated %}
            (<a href="{% url 'restaurantsReviews:dish_create' restaurant.id %}">Add Dish</a>)
        {% endif %}
    </h4>

    <ul>
        {% for dish in restaurant.dishes.all %}
            <li>
                <a href="{% url 'restaurantsReviews:dish_detail' restaurant.id dish.id %}">
                    {{ dish.name }}</a> - ${{ dish.price }}
            </li>
            {% empty %}<li>Sorry, the restaurant hasn't add any dish.</li>
        {% endfor %}

    </ul>

    <br>

    <h4>Comments</h4>
    {% if restaurant.review.all %}
        {% for review in restaurant.review.all %}
            <p>{{ review.rating }} Star, {{ review.user }} said, {{ review.date | date:"Y-m-d" }}</p>
            <p style="margin-left: 40px"> {{ review.comment }}</p>
        {% endfor %}
    {% else %}
        <p style="margin-left: 40px">There is no comment to this restaurant yet.</p>
    {% endif %}

    <h5>Add Comment</h5>
    {% if request.user.is_authenticated %}
        <form action="{% url 'restaurantsReviews:review_create' restaurant.id %}" method="post">
            {% csrf_token %}
                <textarea name="review" id="comment"></textarea>
            <p>Rating <br>
                {% for rate in RATING_CHOICE %}
                    <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.0 }}" />
                    <label for="choice{{ forloop.counter }}">{{ rate.0 }} Star</label>
                    <br>
                {% endfor %}
            </p>
            <input type="submit" value="Submit"/>
        </form>
    {% endif %}
    </h4>

{% endblock %}

restaurantsReviews/templates/restaurantsReviews/restaurant_list.html
{% extends "restaurantsReviews/base.html" %}

{% block content %}
    <h3>Restaurants List</h3>
    
    <ul>
    {% for restaurant in latest_restaurant_list %}
        <li>
            <a href="{% url 'restaurantsReviews:restaurant_detail' restaurant.id %}">
                {{ restaurant.name }}
            </a>
        </li>
        {% empty %}<li>Sorry, there is no restaurant.</li>
    {% endfor %}
    </ul>

    {% if request.user.is_authenticated %}
        <p>
            <span class="glyphicon glyphicon-plus"></span>
            <a href="{% url 'restaurantsReviews:restaurant_create' %}">Add Restaurant</a>
        </p>
    {% else %}
        <p>
            Please <a href="{% url 'account_login' %}?next={% url 'restaurantsReviews:restaurant_create' %}">log in first, </a>
            then add restaurant.
        </p>
    {% endif %}
        

{% endblock %}

restaurantsReviews/templates/restaurantsReviews/restaurant_search.html
{% extends 'restaurantsReviews/base.html' %}

{% block content %}
<h3>Search</h3>

    <form action="" role="search" method="get">
    {% csrf_token %}
    <div class="input-group col-md-12">
        <input type="text" name="q" id="q" class="form-control" placeholder="Search name for restaurants">
        <span class="input-group-btn">
            <button class="btn btn-default form-control" type="submit" value="search">
                <span class="glyphicon glyphicon-search"></span>
            </button>
        </span>
    </div>
    </form>

    <br>

    <table clas="table table-striped" id="result">
    {% if latest_restaurant_list %}
        <thead>
        <tr>
            <th>Restaurant</th>
        </tr>
        </thead>

        <tbody>
        {% for restaurant in latest_restaurant_list %}
            <tr>
                <td>
                    <a href="{% url 'restaurantsReviews:restaurant_detail' restaurant.id %}">
                    {{ restaurant.name }}
                </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    {% endif %}
    </table>
{% endblock %}

{% block js %}
    <script>
    $("#q").bind('input propertychange', function() {
        var q = $(this).val();
        
        $.ajax({
            url:'/restaurantsReviews/ajax/search',
            data: {
                'q': q,
            },
            type: 'GET',
            dataType: 'json',
            sccess:function (data) {
                var content='<thead><tr>'+
                        '<th>Restaurant</th>'+
                        '</tr></thead><tbody>';
                $.each(data, function (i, item) {
                    content=content+
                            '<tr><td>'+
                            item['name']+
                            '</td><tr>'
                });
                content = content + "</tbody>"
                $('#reslt').html(content)
            },
        });
    };
    </script>
{% endblock %}